name: Node CI

on:
  push:
    branches: "main"
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Make git push
      - uses: actions/checkout@v3
      - run: make install
      - run: make lint
